name: GitHub Organization Git Audit Log for Members Report Action
description: 'An Action to generate a report with the total of Git clones, pushes and fetches per organization member for a set interval.'

inputs:
  token:
    description: 'A Personal Access token with repo and read:org scope'
    required: true
  org:
    description: 'Custom GitHub organization to retrieve data for'
    default: ''
    required: false
  days:
    description: 'Amount of days in the past to collect Git audit log data for (max 7 days)'
    default: '7'
    required: false
  sort:
    description: 'Select sorting column'
    # gitClone, gitPush, gitFetch
    default: 'gitClone'
    required: false
  committer-name:
    description: 'The name of the committer that will appear in the Git history'
    default: 'github-actions'
    required: false
  committer-email:
    description: 'The committer email that will appear in the Git history'
    default: 'github-actions@github.com'
    required: false
  fromdate:
    description: 'The date from which to start collecting data'
    required: false
  todate:
    description: 'The date to which to stop collecting data'
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'list'
  color: 'blue'
